let games = [
  {
    id: "1",
    title: "The Witcher 3: Wild Hunt",
    description:
      "The Witcher 3: Wild Hunt is a third-person action RPG with a focus on combat and exploration.",
    price: 59.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "PS4", "Xbox One"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Red Dead Redemption 2",
    description:
      "An epic tale of life in America's unforgiving heartland, featuring a vast and atmospheric world.",
    price: 59.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "PS4", "Xbox One"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "God of War Ragnarök",
    description:
      "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go.",
    price: 69.99,
    image: "https://via.placeholder.com/150",
    platform: ["PS4", "PS5"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Elden Ring",
    description:
      "An action RPG set in a fantasy world created by FromSoftware and George R. R. Martin.",
    price: 59.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Cyberpunk 2077",
    description:
      "An open-world action-adventure story set in Night City, a megalopolis obsessed with power and glamour.",
    price: 49.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "The Legend of Zelda: Tears of the Kingdom",
    description:
      "Explore the vast land and skies of Hyrule in Nintendo's acclaimed action-adventure sequel.",
    price: 69.99,
    image: "https://via.placeholder.com/150",
    platform: ["Nintendo Switch"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    title: "Final Fantasy XVI",
    description:
      "A dark fantasy RPG featuring intense action combat and an epic story of revenge and redemption.",
    price: 69.99,
    image: "https://via.placeholder.com/150",
    platform: ["PS5"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    title: "Starfield",
    description:
      "Bethesda's epic science fiction RPG set among the stars, featuring space exploration and adventure.",
    price: 69.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "Xbox Series X/S"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    title: "Marvel's Spider-Man 2",
    description:
      "Swing through New York City as Peter Parker and Miles Morales in this superhero adventure.",
    price: 69.99,
    image: "https://via.placeholder.com/150",
    platform: ["PS5"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    title: "Baldur's Gate 3",
    description:
      "A next-generation RPG set in the Dungeons & Dragons universe with turn-based combat.",
    price: 59.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "PS5"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    title: "Resident Evil 4 Remake",
    description:
      "A complete remake of the survival horror classic with modern graphics and gameplay mechanics.",
    price: 59.99,
    image: "https://via.placeholder.com/150",
    platform: ["PC", "PS4", "PS5", "Xbox Series X/S"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    title: "Horizon Forbidden West",
    description:
      "Continue Aloy's journey in a majestic but dangerous frontier that conceals mysterious new threats.",
    price: 59.99,
    image: "https://via.placeholder.com/150",
    platform: ["PS4", "PS5"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

let authors = [
  {
    id: "1",
    name: "Sarah Chen",
    verified: true,
  },
  {
    id: "2",
    name: "Michael Rodriguez",
    verified: true,
  },
  {
    id: "3",
    name: "Emma Thompson",
    verified: false,
  },
  {
    id: "4",
    name: "James Wilson",
    verified: true,
  },
  {
    id: "5",
    name: "Akiko Tanaka",
    verified: false,
  },
];

let reviews = [
  {
    id: "1",
    rating: 9,
    content:
      "This game is a masterpiece! The graphics and storyline are incredible.",
    gameId: "1",
    authorId: "1",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    rating: 8,
    content: "Great gameplay mechanics, but could use more content.",
    gameId: "6",
    authorId: "1",
    createdAt: "2024-01-20",
    updatedAt: "2024-01-21",
  },
  {
    id: "3",
    rating: 7,
    content: "Solid game with room for improvement.",
    gameId: "8",
    authorId: "2",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
  },
  {
    id: "4",
    rating: 10,
    content: "Absolutely stunning! A must-play for any gaming enthusiast.",
    gameId: "2",
    authorId: "3",
    createdAt: "2024-02-05",
    updatedAt: "2024-02-05",
  },
  {
    id: "5",
    rating: 6,
    content: "Decent game but doesn't live up to the hype.",
    gameId: "9",
    authorId: "4",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    id: "6",
    rating: 8,
    content: "Impressive visuals and engaging story.",
    gameId: "7",
    authorId: "5",
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15",
  },
  {
    id: "7",
    rating: 9,
    content: "One of the best games I've played this year!",
    gameId: "8",
    authorId: "1",
    createdAt: "2024-02-20",
    updatedAt: "2024-02-20",
  },
  {
    id: "8",
    rating: 7,
    content: "Good game but has some technical issues.",
    gameId: "9",
    authorId: "2",
    createdAt: "2024-02-25",
    updatedAt: "2024-02-25",
  },
  {
    id: "9",
    rating: 8,
    content: "Really enjoyed the multiplayer features.",
    gameId: "3",
    authorId: "3",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
  },
  {
    id: "10",
    rating: 9,
    content: "Amazing attention to detail and world-building.",
    gameId: "10",
    authorId: "4",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
  },
  {
    id: "11",
    rating: 8,
    content: "Good game but has some technical issues.",
    gameId: "11",
    authorId: "5",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
  },
  {
    id: "12",
    rating: 9,
    content: "Amazing attention to detail and world-building.",
    gameId: "12",
    authorId: "1",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
  },
];

export { games, authors, reviews };
